### ISSUE TITLE
能使用更多C++的特性吗?

### ISSUE THREAD

**Issue by FurryR** [yangtau/hedgehog#30]
比如使用string代替const char*,左值引用代替指针并更少地在程序中使用malloc/new/free/delete,从而删除一些不必要的实现并提升程序的可读性...原谅菜逼看不懂大佬的代码实现

**Comment by yangtau** [comment]
我希望能用纯 C 语言来实现。
C++的 string 之类的std库实现用起来虽然方便，但是它屏蔽了字符串底层的实现细节，我就不能根据自己的需求做优化（例如实现 string pool来提升字符串操作的性能）。

**Comment by yangtau** [comment]
恰好最近有一些想法，我会考虑单独写一个用C++实现的语言，单纯作为一个示例，从而不用考虑太多关于优化之类的问题。
例外，如果你想学习编译器的实现，推荐这个博客 [craftinginterpreters](http://craftinginterpreters.com)，这个项目很多实现的源来。

**Comment by FurryR** [comment]
我根据大佬的设计也做了个解析器，不过十分垃圾，效果也不好，还容易段错误...

**Comment by yangtau** [comment]
哈哈哈，那可能需要 Debug 一下。
